### ISSUE TITLE
Cannot see the subtasks

### ISSUE THREAD

**Issue by buildaworld** [fbgallet/roam-extension-calendar#1]
DNP
1. add task 
![DNP1](https://github.com/user-attachments/assets/e8ae7c6a-4f9f-4bc0-ab51-4655698a6263)
2. after check main task，subtask disappeared.
![DNP2](https://github.com/user-attachments/assets/a1da99ce-888f-4c12-b2ae-bd6238c98504)
3. uncheck main task and refresh，subtasks have still not appeared
![DNP3](https://github.com/user-attachments/assets/96a35a80-023d-4e1d-abd6-7312fb8ee7ff)

another page
Cannot see the subtask
![another page1](https://github.com/user-attachments/assets/2db901be-42f8-451a-93bd-f511212e52f5)

**Comment by fbgallet** [comment]
Indeed, it's a design choice.

It didn't seem relevant to me to show all the subtasks in a calendar (since you can just click on the parent task to see the subtasks), as no hierarchy is directly displayed in the calendar. This could be an option, but it might conflict with managing information from the direct children.

**Comment by buildaworld** [comment]
If possible, I would still like to have the option to toggle the display of subtasks, or only show subtasks that have a date 

For example, when I attend a meeting, I will record the meeting content in the meeting task. For any new tasks added during the meeting, I will record them as new tasks in other to-do lists. However, in Roam, I will directly record them as subtasks. Additionally, the meeting task will be marked as completed.

**Comment by fbgallet** [comment]
I've made some experiments and found a solution to display subtasks as an option (with a date or not). Enabling this option could slow down a bit month or year display in the calendar if you have many blocks in your DNPs.

It will be available in the next update (that I will be submitting very soon for review). Thank you for the suggestion!
