### ISSUE TITLE
Support for 12 hour timestamps

### ISSUE THREAD

**Issue by wireframe** [fbgallet/roam-extension-calendar#2]
Would it be possible to support 12 hour timestamp format (ie: AM/PM)?

I've worked with the google calendar and Nautulis Roam extensions which both support 12 hour timestamp formats.  Would there be a possibility for code reuse?
example:
https://github.com/search?q=repo%3Atombarys%2Froam-depot-nautilus%20time%20parse&type=code

**Comment by fbgallet** [comment]
Hi,
currently you can display timestamps in 12h format in the calendar, but you can only input manually 24h time format and the timestamp recorded in the Roam block will always be in 24h format.

I take note of your feature request, it shouldn't be hard to implement, i will try to add it to the next update. Thanks for the code snippet from Nautilus but Full Calendar is a React/JavaScript app, not a Clojure one.

**Comment by fbgallet** [comment]
12h format is now supported for input timestamps, have a try !
